package axi_test_pkg;
	`include "uvm_macros.svh"
	import uvm_pkg::*;
	import axi_seq_lib_pkg::*;
	import axi_agent_pkg::*;
	import axi_env_pkg::*;
	`include "../test_lib/axi_base_test.sv"
	`include "../test_lib/axi_reset_test.sv"
	`include "../test_lib/axi_write_test.sv"
	`include "../test_lib/axi_read_test.sv"
	`include "../test_lib/axi_rd_wr_test.sv"
	`include "../test_lib/axi_fixed_burst_write_test.sv"
	`include "../test_lib/axi_incr_burst_write_test.sv"
	`include "../test_lib/axi_wrap_burst_write_test.sv"
	`include "../test_lib/axi_fixed_burst_read_test.sv"
	`include "../test_lib/axi_incr_burst_read_test.sv"
	`include "../test_lib/axi_wrap_burst_read_test.sv"
	`include "../test_lib/axi_concurrency_test.sv"
	`include "../test_lib/axi_dummy_test.sv"
endpackage
